#ifndef _LANGUAGE_H_
#define _LANGUAGE_H_

#include <stdint.h>

enum
{
    LANGUAGE_TYPE_ENGLISH, // 英文
    LANGUAGE_TYPE_HanWen,  // 韩文
    LANGUAGE_TYPE_XiBanYa, // 西班牙
    LANGUAGE_TYPE_ALaBo,   // 阿拉伯
    LANGUAGE_TYPE_YueNan,  // 越南语
    LANGUAGE_TYPE_ELuoSi,  // 俄罗斯
    LANGUAGE_TYPE_TOTAL,
};

typedef enum
{
    // layout home
    LAYOUT_LANG_ID_NULL,
    LAYOUT_HOME_LANG_DOOR_CAM_ID,
    LAYOUT_HOME_LANG_CAM_DISCONNET_ID,
    LAYOUT_HOME_LANG_CAM_CONFLICT_ID,
    LAYOUT_HOME_LANG_INTERCOM_ID,
    LAYOUT_HOME_LANG_DUPLICATE_ID,
    LAYOUT_HOME_LANG_MEDIA_ID,
    LAYOUT_HOME_LANG_MUTE_ID,
    LAYOUT_HOME_LANG_SECURITY_ID,
    LAYOUT_HOME_LANG_MON_ID,
    LAYOUT_HOME_LANG_TUE_ID,
    LAYOUT_HOME_LANG_WED_ID,
    LAYOUT_HOME_LANG_THU_ID,
    LAYOUT_HOME_LANG_FRI_ID,
    LAYOUT_HOME_LANG_SAT_ID,
    LAYOUT_HOME_LANG_SUN_ID,
    LAYOUT_HOME_LANG_DEV1_ID,
    LAYOUT_HOME_LANG_DEV2_ID,
    LAYOUT_HOME_LANG_DEV3_ID,
    LAYOUT_HOME_LANG_DEV4_ID,
    LAYOUT_HOME_LANG_DEV_CONFLICT_ID,
    LAYOUT_HOME_LANG_AM_ID,
    LAYOUT_HOME_LANG_PM_ID,

    // layout monitor
    LAYOUT_MONITOR_LANG_CAM1_ID,
    LAYOUT_MONITOR_LANG_CAM2_ID,
    LAYOUT_MONITOR_LANG_ALARM_OPEN_ID,
    LAYOUT_MONITOR_LANG_DOOR_OPEN_ID,
    LAYOUT_MONITOR_LANG_CAM_BUSY_ID,
    LAYOUT_MONITOR_LANG_CAM_SIGNAL_LOSS_ID,
    LAYOUT_MONITOR_LANG_CAM_CONFLICT_ID,
    LAYOUT_MONITOR_LANG_APP_MONITORING_ID,
    LAYOUT_MONITOR_LANG_CALL_FROM_LOBBY_ID,

    // layout intercom
    LAYOUT_INTERCOM_LANG_INTERNAL_CALL_ID,
    LAYOUT_INTERCOM_LANG_DEV_BUSY_ID,

    // layout media
    LAYOUT_MEDIA_LANG_CAM1_ID,
    LAYOUT_MEDIA_LANG_CAM2_ID,
    LAYOUT_MEDIA_LANG_DEL_ALL_PHOTO_ID,
    LAYOUT_MEDIA_LANG_DEL_THIS_PHOTO_ID,

    // layout security
    LAYOUT_SECURITY_LANG_START_ID,
    LAYOUT_SECURITY_LANG_STOP_ID,
    LAYOUT_SECURITY_LANG_ACTIVE_ID,
    LAYOUT_SECURITY_LANG_AFTER_ID,
    LAYOUT_SECURITY_LANG_TIP_ID,
    LAYOUT_SECURITY_LANG_DEL_ALL_ID,

    // layout setting
    LAYOUT_SETTING_LANG_GENERAL_ID,
    LAYOUT_SETTING_LANG_SOUND_ID,
    LAYOUT_SETTING_LANG_NETWORK_ID,
    LAYOUT_SETTING_LANG_MODE_ID,
    LAYOUT_SETTING_LANG_OTHER_ID,
    LAYOUT_SETTING_LANG_RESET_ID,
    // general
    LAYOUT_SETTING_LANG_DEVICE_ID,
    LAYOUT_SETTING_LANG_PHONE_ID,
    LAYOUT_SETTING_LANG_APP_ID,
    LAYOUT_SETTING_LANG_TIME_ID,
    LAYOUT_SETTING_LANG_DATE_ID,
    LAYOUT_SETTING_LANG_NETWORK_TIME_ID,
    LAYOUT_SETTING_LANG_AUTO_SET_ID,
    LAYOUT_SETTING_LANG_LANGUAGE_ID,
    LAYOUT_SETTING_LANG_ENGLISH_ID, // 英文
    LAYOUT_SETTING_LANG_HanWen_ID,  // 韩文
    LAYOUT_SETTING_LANG_XiBanYa_ID, // 西班牙
    LAYOUT_SETTING_LANG_ALaBo_ID,   // 阿拉伯
    LAYOUT_SETTING_LANG_YueNan_ID,  // 越南语
    LAYOUT_SETTING_LANG_ELuoSi_ID,  // 俄罗斯
    LAYOUT_SETTING_LANG_CLOSE_APP_TIP_ID,
    LAYOUT_SETTING_LANG_NOTICE_ID,
    LAYOUT_SETTING_LANG_AUTO_SYNC_TIME_TIP1_ID,
    LAYOUT_SETTING_LANG_AUTO_SYNC_TIME_TIP2_ID,
    LAYOUT_SETTING_LANG_APP_LINK_CONFLICT_TIP1_ID,
    LAYOUT_SETTING_LANG_APP_LINK_CONFLICT_TIP2_ID,
    LAYOUT_SETTING_LANG_WHETHER_CHANGE_DEV_ID_ID,
    // sound
    LAYOUT_SETTING_LANG_CAMERA1_ID,
    LAYOUT_SETTING_LANG_CAMERA2_ID,
    LAYOUT_SETTING_LANG_INTERCOM_ID,
    LAYOUT_SETTING_LANG_CALL_VOL_ID,
    LAYOUT_SETTING_LANG_TALK_VOL_ID,
    LAYOUT_SETTING_LANG_CALL_RING_ID,
    LAYOUT_SETTING_LANG_SPK_SENSITIVITY_ID,
    LAYOUT_SETTING_LANG_MIC_SENSITIVITY_ID,

    // wifi
    LAYOUT_SETTING_LANG_WIFI_ID,
    LAYOUT_SETTING_LANG_WIFI_ADD_ID,
    LAYOUT_SETTING_LANG_WIFI_CONNECTED_ID,
    LAYOUT_SETTING_LANG_WIFI_CONNECTING_ID,
    LAYOUT_SETTING_LANG_WIFI_NEXT_ID,
    LAYOUT_SETTING_LANG_WIFI_PREV_ID,
    LAYOUT_SETTING_LANG_WIFI_CONNECT_SUCCESS_ID,
    LAYOUT_SETTING_LANG_WIFI_CONNECT_FAILED_ID,
    LAYOUT_SETTING_LANG_WIFI_NOT_FOUND_ID,
    LAYOUT_SETTING_LANG_WIFI_INPUT_EMPTY_ID,

    LAYOUT_SETTING_LANG_WIFI_NAME_ID,
    LAYOUT_SETTING_LANG_WIFI_PWD_ID,
    LAYOUT_SETTING_LANG_WIFI_NAME_ENTER_ID,
    LAYOUT_SETTING_LANG_WIFI_PWD_ENTER_ID,
    LAYOUT_SETTING_LANG_WIFI_SSID_EMPTY_ID,
    LAYOUT_SETTING_LANG_WIFI_WRONG_PWD_ID,
    LAYOUT_SETTING_LANG_WIFI_PWD_TOO_SHORT_ID,

    // mode
    LAYOUT_SETTING_LANG_AUTO_REC_ID,
    LAYOUT_SETTING_LANG_ALWAYS_ON_DISP_ID,
    LAYOUT_SETTING_LANG_ABSENT_SETTING_TIME_ID,
    LAYOUT_SETTING_LANG_MONITORING_TIME_ID,
    LAYOUT_SETTING_LANG_DOOR_OPEN_TIME_ID,

    // other
    LAYOUT_SETTING_LANG_SCREEN_BRIGHTNESS_ID,
    LAYOUT_SETTING_LANG_MODIFY_PWD_ID,
    LAYOUT_SETTING_LANG_SYSTEM_INFO_ID,
    LAYOUT_SETTING_LANG_MANUAL_DOWNLOAD_ID,
    // LAYOUT_SETTING_LANG_STORAGE_INFO_ID,
    LAYOUT_SETTING_LANG_OUTDOOR_UPGRADE_ID,
    LAYOUT_SETTING_LANG_MULTI_GENERATIONAL_MODE_ID,

    // modify pwd
    LAYOUT_SETTING_LANG_OLD_ID,
    LAYOUT_SETTING_LANG_OLD_PWD_ID,
    LAYOUT_SETTING_LANG_NEW_ID,
    LAYOUT_SETTING_LANG_NEW_PWD_ID,
    LAYOUT_SETTING_LANG_MODIFY_SUCCESS_ID,
    LAYOUT_SETTING_LANG_WHETHER_MODIFY_PWD_ID,

    // system info
    LAYOUT_SETTING_LANG_SYSTEM_VERSION_ID,
    LAYOUT_SETTING_LANG_CAM1_VERSION_ID,
    LAYOUT_SETTING_LANG_CAM2_VERSION_ID,
    LAYOUT_SETTING_LANG_IP_ADDR_ID,
    LAYOUT_SETTING_LANG_SERIAL_NUMBER_ID,
    LAYOUT_SETTING_LANG_TUYA_UUID_ID,

    LAYOUT_SETTING_LANG_UPGRADE_CHECK_ID,
    LAYOUT_SETTING_LANG_UPGRADE_TRANSFERRING_ID,
    LAYOUT_SETTING_LANG_UPGRADE_TRANSFER_FAIL_ID,
    LAYOUT_SETTING_LANG_UPGRADE_FILE_DAMAGED_ID,
    LAYOUT_SETTING_LANG_UPGRADE_TRANSFER_COMPLETED_ID,

    // apartment
    LAYOUT_SETTING_LANG_INPUT_PWD_ID,
    LAYOUT_SETTING_LANG_ADMIN_PWD_ID,
    LAYOUT_SETTING_LANG_WRONG_PWD_ID,
    LAYOUT_SETTING_LANG_REGIST_TIP_ID,
    LAYOUT_SETTING_LANG_APTM_SETTING_ID,
    LAYOUT_SETTING_LANG_AUTO_REGIST_ID,
    LAYOUT_SETTING_LANG_MANUAL_REGIST_ID,
    LAYOUT_SETTING_LANG_SERVER_SETTING_ID,
    LAYOUT_SETTING_LANG_REGIST_SUCCESS_REBOOT_ID,
    LAYOUT_SETTING_LANG_REGIST_SUCCESS_ID,
    LAYOUT_SETTING_LANG_REGIST_FAILED_ID,
    LAYOUT_SETTING_LANG_APTM_NAME_ID,
    LAYOUT_SETTING_LANG_SEARCH_APTM_ID,
    LAYOUT_SETTING_LANG_SERVER_IP_ID,
    LAYOUT_SETTING_LANG_API_PORT_ID,
    LAYOUT_SETTING_LANG_SIP_PORT_ID,
    LAYOUT_SETTING_LANG_ACCOUNT_ID,
    LAYOUT_SETTING_LANG_PASSWORD_ID,
    LAYOUT_SETTING_LANG_PROXY_ID,
    LAYOUT_SETTING_LANG_UNIT_NUM_ID,
    LAYOUT_SETTING_LANG_ROOM_NUM_ID,
    LAYOUT_SETTING_LANG_INPUT_UNIT_NUM_ID,
    LAYOUT_SETTING_LANG_INPUT_ROOM_NUM_ID,

    // system reset
    LAYOUT_SETTING_LANG_WHETHER_RESET_ID,
    LAYOUT_SETTING_LANG_RESETTING_ID,

    // tuya
    LAYOUT_TUYA_LANG_DOOR1_CURR_ID,
    LAYOUT_TUYA_LANG_DOOR1_ID,
    LAYOUT_TUYA_LANG_DOOR2_CURR_ID,
    LAYOUT_TUYA_LANG_DOOR2_ID,

    // ota
    LAYOUT_OTA_LANG_UPDATING_ID,
    LAYOUT_OTA_LANG_UPDATING_TIP_ID,
    LAYOUT_OTA_LANG_NOT_FOUND_SDCARD_ID,
    LAYOUT_OTA_LANG_FILE_CREATE_FAIL_ID,
    LAYOUT_OTA_LANG_FILE_CHECK_FAIL_ID,
    LAYOUT_OTA_LANG_FILE_DOWNLOAD_FINISH_ID,

    // common
    COMMON_LANG_LOBBY_ID,
    COMMON_LANG_DEV1_ID,
    COMMON_LANG_DEV2_ID,
    COMMON_LANG_DEV3_ID,
    COMMON_LANG_DEV4_ID,
    COMMON_LANG_SENSOR1_ID,
    COMMON_LANG_SENSOR2_ID,
    COMMON_LANG_APPROVAL_ID,
    COMMON_LANG_BACK_ID,
    COMMON_LANG_OFF_ID,
    COMMON_LANG_ON_ID,
    COMMON_LANG_YES_ID,
    COMMON_LANG_NO_ID,
    COMMON_LANG_INPUT_EMPTY_ID,
    COMMON_LANG_AUTHENTICATION_FAILED_ID,
    COMMON_LANG_PASSWORD_ID,
    COMMON_LANG_COMFIRM_ID,
    COMMON_LANG_QUIT_ID,
    COMMON_LANG_WARNING_ID,

    LANGUAGE_STRING_ID_TOTAL,
} layout_lang_id;

const char *language_string_get(layout_lang_id id);

void language_num_to_BaiJamjuree(const char *str, char *buf);

#endif // _LANGUAGE_H_